"""Initial infrastructure models

Revision ID: c3ad36bb186f
Revises:
Create Date: 2026-07-09 21:02:03.104880

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c3ad36bb186f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
