.DEFAULT_GOAL := help

.PHONY: setup sync install dev api docker-up docker-down docker-reset docker-logs docker-status db-current db-history db-upgrade db-downgrade db-revision format lint typecheck test quality clean help

# ==============================================================================
# Environment Setup
# ==============================================================================

setup: ## Create/update the uv environment and install development tools.
	uv sync

sync: setup ## Alias for setup.

install: setup ## Alias for setup.

# ==============================================================================
# Execution
# ==============================================================================

dev: ## Run the API factory for local development.
	uv run uvicorn apps.api.app.main:app --reload

api: dev ## Alias for dev.

# ==============================================================================
# Docker Lifecycle
# ==============================================================================

docker-up: ## Start local infrastructure containers.
	docker compose up -d

docker-down: ## Stop local infrastructure containers.
	docker compose down

docker-reset: ## Stop containers, remove volumes, and restart.
	docker compose down -v
	docker compose up -d

docker-logs: ## View container logs.
	docker compose logs -f

docker-status: ## View container status.
	docker compose ps

# ==============================================================================
# Database Migrations
# ==============================================================================

db-current: ## Show current database revision.
	uv run alembic current

db-history: ## Show migration history.
	uv run alembic history

db-upgrade: ## Upgrade database to the latest revision.
	uv run alembic upgrade head

db-downgrade: ## Downgrade database by one revision.
	uv run alembic downgrade -1

db-revision: ## Create a new autogenerated revision (Usage: make db-revision MSG="description")
	uv run alembic revision --autogenerate -m "$(MSG)"

# ==============================================================================
# Quality Gates
# ==============================================================================

format: ## Format Python source with Ruff.
	uv run ruff format .

lint: ## Run Ruff lint checks.
	uv run ruff check .

typecheck: ## Run strict MyPy checks.
	uv run mypy

test: ## Run the test suite.
	uv run pytest

quality: format lint typecheck test ## Run all quality gates.

# ==============================================================================
# Maintenance
# ==============================================================================

clean: ## Remove repository-local Python caches and coverage output.
	uv run --no-sync python -c "from pathlib import Path; import shutil; names={'__pycache__','.mypy_cache','.pytest_cache','.ruff_cache','htmlcov'}; [shutil.rmtree(path, ignore_errors=True) for path in Path('.').rglob('*') if path.is_dir() and path.name in names]; [path.unlink(missing_ok=True) for path in Path('.').glob('.coverage*')]"

help: ## Show available commands.
	@echo "Kogniq development commands:"
	@awk 'BEGIN {FS = ":.*## "}; /^[a-zA-Z_-]+:.*## / {printf "  %-15s %s\n", $$1, $$2}' $(MAKEFILE_LIST)
