"use client";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import * as DropdownMenuPrimitive from "@radix-ui/react-dropdown-menu";
import * as TooltipPrimitive from "@radix-ui/react-tooltip";
import { X } from "lucide-react";
import type { ReactNode } from "react";
import { cn } from "@/lib/utils";
import { IconButton } from "./button";

function Overlay({ children }: { children: ReactNode }) { return <DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-ink/25 data-[state=open]:animate-in" />{children}</DialogPrimitive.Portal>; }
export function Dialog({ open, onOpenChange, title, description, children, trigger }: { open?: boolean; onOpenChange?: (open: boolean) => void; title: string; description?: string; children: ReactNode; trigger?: ReactNode }) { return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Trigger asChild>{trigger}</DialogPrimitive.Trigger><Overlay><DialogPrimitive.Content className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-md border bg-surface p-5 shadow-overlay"><div className="mb-4 flex items-start justify-between gap-4"><div><DialogPrimitive.Title className="text-base font-semibold">{title}</DialogPrimitive.Title>{description && <DialogPrimitive.Description className="mt-1 text-sm text-muted">{description}</DialogPrimitive.Description>}</div><DialogPrimitive.Close asChild><IconButton label="Close dialog"><X className="size-4" /></IconButton></DialogPrimitive.Close></div>{children}</DialogPrimitive.Content></Overlay></DialogPrimitive.Root>; }
export function Drawer({ open, onOpenChange, title, children, trigger }: { open?: boolean; onOpenChange?: (open: boolean) => void; title: string; children: ReactNode; trigger?: ReactNode }) { return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Trigger asChild>{trigger}</DialogPrimitive.Trigger><Overlay><DialogPrimitive.Content className="fixed inset-y-0 right-0 z-50 w-full max-w-md border-l bg-surface p-5 shadow-overlay"><div className="mb-5 flex items-center justify-between"><DialogPrimitive.Title className="text-base font-semibold">{title}</DialogPrimitive.Title><DialogPrimitive.Close asChild><IconButton label="Close panel"><X className="size-4" /></IconButton></DialogPrimitive.Close></div>{children}</DialogPrimitive.Content></Overlay></DialogPrimitive.Root>; }
export function Tooltip({ content, children }: { content: string; children: ReactNode }) { return <TooltipPrimitive.Provider delayDuration={350}><TooltipPrimitive.Root><TooltipPrimitive.Trigger asChild>{children}</TooltipPrimitive.Trigger><TooltipPrimitive.Portal><TooltipPrimitive.Content sideOffset={6} className="z-[70] rounded-xs bg-ink px-2 py-1 text-xs text-surface shadow-overlay">{content}<TooltipPrimitive.Arrow className="fill-ink" /></TooltipPrimitive.Content></TooltipPrimitive.Portal></TooltipPrimitive.Root></TooltipPrimitive.Provider>; }
export function Dropdown({ trigger, items }: { trigger: ReactNode; items: { label: string; onSelect?: () => void; destructive?: boolean }[] }) { return <DropdownMenuPrimitive.Root><DropdownMenuPrimitive.Trigger asChild>{trigger}</DropdownMenuPrimitive.Trigger><DropdownMenuPrimitive.Portal><DropdownMenuPrimitive.Content align="end" sideOffset={6} className="z-[70] min-w-40 rounded-sm border bg-surface p-1 shadow-overlay">{items.map((item) => <DropdownMenuPrimitive.Item key={item.label} onSelect={item.onSelect} className={cn("cursor-default rounded-xs px-2.5 py-2 text-sm outline-none data-[highlighted]:bg-raised", item.destructive && "text-danger")}>{item.label}</DropdownMenuPrimitive.Item>)}</DropdownMenuPrimitive.Content></DropdownMenuPrimitive.Portal></DropdownMenuPrimitive.Root>; }
