from dataclasses import dataclass, field
from datetime import UTC, datetime

from ..value_objects import AIMetadata, ConceptId, LearningPathId, generate_id


@dataclass
class LearningPath:
    """
    Domain concept for a sequence of concepts to be learned by a student.
    Can be dynamically generated by the Recommendation Engine and persisted here.
    """

    student_id: str
    id: LearningPathId = field(default_factory=lambda: LearningPathId(generate_id()))
    ordered_concept_ids: list[ConceptId] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    ai_metadata: AIMetadata = field(default_factory=AIMetadata)
