from typing import Any, Protocol


class RetryPolicy(Protocol):
    @property
    def max_retries(self) -> int: ...

    @property
    def delay_seconds(self) -> int: ...


class StageResult(Protocol):
    @property
    def success(self) -> bool: ...

    @property
    def data(self) -> dict[str, Any]: ...

    @property
    def error(self) -> str | None: ...


class PipelineContext(Protocol):
    @property
    def document_id(self) -> str: ...

    @property
    def metadata(self) -> dict[str, Any]: ...

    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...


class PipelineStage(Protocol):
    @property
    def stage_name(self) -> str: ...

    async def can_skip(self, context: PipelineContext) -> bool: ...

    async def execute(self, context: PipelineContext) -> StageResult: ...

    def retry_policy(self) -> RetryPolicy: ...
